/**
 * API layer for fetching tweet data.
 *
 * Uses local JSON data from bangers_tweets.json.
 * Data is generated by: scratchpads/23_generate_bangers_data.py
 *
 * For future real-time integration, see CLAUDE.md.
 */

import { loadBangersData, recordToTweet } from './localData';
import { Tweet } from './types';

// Simple in-memory caches to avoid redundant lookups
const tweetCache = new Map<string, Tweet>();
const threadCache = new Map<string, Tweet[]>();
const quotesCache = new Map<string, Tweet[]>();
const conversationIdCache = new Map<string, string | null>();

// Cache TTL in milliseconds (5 minutes)
const CACHE_TTL = 5 * 60 * 1000;
const cacheTimestamps = new Map<string, number>();

function isCacheValid(key: string): boolean {
  const timestamp = cacheTimestamps.get(key);
  if (!timestamp) return false;
  return Date.now() - timestamp < CACHE_TTL;
}

function setCacheTimestamp(key: string) {
  cacheTimestamps.set(key, Date.now());
}

/**
 * Fetch tweet details for a list of tweet IDs.
 */
export async function fetchTweetDetails(tweetIds: string[]): Promise<Tweet[]> {
  if (tweetIds.length === 0) return [];

  const data = await loadBangersData();

  // Check cache for already-fetched tweets
  const cachedTweets: Tweet[] = [];
  const missingIds: string[] = [];

  for (const id of tweetIds) {
    const cacheKey = `tweet:${id}`;
    if (tweetCache.has(id) && isCacheValid(cacheKey)) {
      cachedTweets.push(tweetCache.get(id)!);
    } else {
      missingIds.push(id);
    }
  }

  // If all tweets are cached, return them in order
  if (missingIds.length === 0) {
    return tweetIds.map(id => tweetCache.get(id)!).filter(Boolean);
  }

  // Fetch missing tweets from local data
  const newTweets: Tweet[] = [];

  for (const id of missingIds) {
    const record = data.tweets[id];
    if (!record) continue;

    // Get quoted tweet if exists
    const quotedId = data.quoteRelationships.quotedBy[id];
    let quotedTweet: Tweet | undefined;

    if (quotedId) {
      const quotedRecord = data.tweets[quotedId];
      if (quotedRecord) {
        quotedTweet = recordToTweet(quotedRecord);
      }
    }

    const tweet = recordToTweet(record, quotedTweet);
    tweet.quoted_tweet_id = quotedId;

    // Cache the tweet
    tweetCache.set(id, tweet);
    setCacheTimestamp(`tweet:${id}`);
    newTweets.push(tweet);
  }

  // Return all tweets in original order
  return tweetIds
    .map(id => tweetCache.get(id) || newTweets.find(t => t.tweet_id === id))
    .filter((t): t is Tweet => t !== undefined);
}

/**
 * Get all tweets in a conversation thread.
 */
export async function getThread(conversationId: string): Promise<Tweet[]> {
  // Check cache first
  const cacheKey = `thread:${conversationId}`;
  if (threadCache.has(conversationId) && isCacheValid(cacheKey)) {
    return threadCache.get(conversationId)!;
  }

  const data = await loadBangersData();
  const tweetIds = data.conversations[conversationId] || [];

  if (tweetIds.length === 0) {
    threadCache.set(conversationId, []);
    setCacheTimestamp(cacheKey);
    return [];
  }

  const tweets = await fetchTweetDetails(tweetIds);

  // Sort by date
  tweets.sort((a, b) => new Date(a.created_at).getTime() - new Date(b.created_at).getTime());

  // Add conversation_id to all
  const result = tweets.map(t => ({ ...t, conversation_id: conversationId }));

  // Cache result
  threadCache.set(conversationId, result);
  setCacheTimestamp(cacheKey);

  return result;
}

/**
 * Get all tweets that quote a given tweet.
 */
export async function getQuotes(tweetId: string): Promise<Tweet[]> {
  // Check cache first
  const cacheKey = `quotes:${tweetId}`;
  if (quotesCache.has(tweetId) && isCacheValid(cacheKey)) {
    return quotesCache.get(tweetId)!;
  }

  const data = await loadBangersData();
  const quoteIds = data.quoteRelationships.quotesOf[tweetId] || [];

  if (quoteIds.length === 0) {
    quotesCache.set(tweetId, []);
    setCacheTimestamp(cacheKey);
    return [];
  }

  const result = await fetchTweetDetails(quoteIds);

  // Cache result
  quotesCache.set(tweetId, result);
  setCacheTimestamp(cacheKey);

  return result;
}

/**
 * Get the conversation ID for a tweet.
 */
export async function getConversationId(tweetId: string): Promise<string | null> {
  // Check cache first
  const cacheKey = `convId:${tweetId}`;
  if (conversationIdCache.has(tweetId) && isCacheValid(cacheKey)) {
    return conversationIdCache.get(tweetId)!;
  }

  const data = await loadBangersData();
  const convId = data.tweetToConversation[tweetId] || null;

  // Cache result
  conversationIdCache.set(tweetId, convId);
  setCacheTimestamp(cacheKey);

  return convId;
}

/**
 * Batch fetch conversation IDs for multiple tweets.
 */
export async function getConversationIds(tweetIds: string[]): Promise<Map<string, string | null>> {
  const result = new Map<string, string | null>();
  const missingIds: string[] = [];

  // Check cache first
  for (const id of tweetIds) {
    const cacheKey = `convId:${id}`;
    if (conversationIdCache.has(id) && isCacheValid(cacheKey)) {
      result.set(id, conversationIdCache.get(id)!);
    } else {
      missingIds.push(id);
    }
  }

  if (missingIds.length === 0) {
    return result;
  }

  // Fetch from local data
  const data = await loadBangersData();

  for (const id of missingIds) {
    const convId = data.tweetToConversation[id] || null;
    conversationIdCache.set(id, convId);
    setCacheTimestamp(`convId:${id}`);
    result.set(id, convId);
  }

  return result;
}

/**
 * Batch fetch threads for multiple conversation IDs.
 */
export async function getThreadsBatch(conversationIds: string[]): Promise<Map<string, Tweet[]>> {
  const result = new Map<string, Tweet[]>();
  const missingConvIds: string[] = [];

  // Check cache first
  for (const convId of conversationIds) {
    const cacheKey = `thread:${convId}`;
    if (threadCache.has(convId) && isCacheValid(cacheKey)) {
      result.set(convId, threadCache.get(convId)!);
    } else {
      missingConvIds.push(convId);
    }
  }

  if (missingConvIds.length === 0) {
    return result;
  }

  // Fetch each missing thread
  for (const convId of missingConvIds) {
    const thread = await getThread(convId);
    result.set(convId, thread);
  }

  return result;
}
