/**
 * Local data loader for Bangers website.
 *
 * Loads tweet data from bangers_tweets.json instead of Supabase.
 * This enables offline operation when Supabase is paused/unavailable.
 *
 * Data is generated by: scratchpads/23_generate_bangers_data.py
 */

import { Tweet } from './types';

// Types for the local data structure
export interface TweetRecord {
  tweet_id: string;
  created_at?: string;
  full_text?: string;
  username?: string;
  avatar_media_url?: string;
  favorite_count?: number;
  retweet_count?: number;
  quote_count?: number;
  archive_quote_count?: number;
  is_archive_user?: boolean;
  reply_to_tweet_id?: string;
  reply_to_user_id?: string;
  reply_to_username?: string;
  media_urls?: string[];
  // From atlas data
  strand_id?: string;
  annotation?: string;
  is_essential?: boolean;
}

export interface BangersData {
  generatedAt: string;
  tweetCount: number;
  tweets: Record<string, TweetRecord>;
  byYear: Record<string, string[]>;  // year -> tweet_ids sorted by score
  quoteRelationships: {
    quotesOf: Record<string, string[]>;  // original_tweet -> [quoting_tweets]
    quotedBy: Record<string, string>;    // quoting_tweet -> original_tweet
  };
  conversations: Record<string, string[]>;  // conversation_id -> tweet_ids
  tweetToConversation: Record<string, string>;  // tweet_id -> conversation_id
  replies: Record<string, string>;  // tweet_id -> parent_tweet_id
}

// Server-side singleton cache
let cachedData: BangersData | null = null;
let loadPromise: Promise<BangersData> | null = null;

/**
 * Get the base URL for fetching data.
 * On server, use file system. On client, use relative URL.
 */
function getDataUrl(): string {
  // In browser, use relative path
  if (typeof window !== 'undefined') {
    return '/bangers_tweets.json';
  }
  // On server during build/runtime, use absolute URL if available
  // or file path for local development
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || process.env.VERCEL_URL;
  if (baseUrl) {
    const protocol = baseUrl.startsWith('http') ? '' : 'https://';
    return `${protocol}${baseUrl}/bangers_tweets.json`;
  }
  // Fallback for local development - use file system
  return 'file://localhost/bangers_tweets.json';
}

/**
 * Load the bangers_tweets.json data file.
 * Uses singleton pattern for caching.
 */
export async function loadBangersData(): Promise<BangersData> {
  // Return cached data if available
  if (cachedData) {
    return cachedData;
  }

  // Return existing promise if loading in progress
  if (loadPromise) {
    return loadPromise;
  }

  // Start loading
  loadPromise = (async () => {
    try {
      // Check if we're on server and can use fs
      if (typeof window === 'undefined') {
        // Server-side: use fs for reliability
        const fs = await import('fs');
        const path = await import('path');
        const dataPath = path.join(process.cwd(), 'public/bangers_tweets.json');
        const fileContent = fs.readFileSync(dataPath, 'utf-8');
        const data: BangersData = JSON.parse(fileContent);
        cachedData = data;
        console.log(`[localData] Loaded ${data.tweetCount} tweets from local file`);
        return data;
      } else {
        // Client-side: use fetch
        const response = await fetch('/bangers_tweets.json');
        if (!response.ok) {
          throw new Error(`Failed to fetch data: ${response.status}`);
        }
        const data: BangersData = await response.json();
        cachedData = data;
        console.log(`[localData] Loaded ${data.tweetCount} tweets via fetch`);
        return data;
      }
    } catch (error) {
      console.error('[localData] Failed to load bangers_tweets.json:', error);
      // Return empty data structure on error
      return {
        generatedAt: '',
        tweetCount: 0,
        tweets: {},
        byYear: {},
        quoteRelationships: { quotesOf: {}, quotedBy: {} },
        conversations: {},
        tweetToConversation: {},
        replies: {},
      };
    }
  })();

  return loadPromise;
}

/**
 * Convert a TweetRecord from local data to a Tweet object.
 */
export function recordToTweet(record: TweetRecord, quotedTweet?: Tweet): Tweet {
  // Extract year from created_at if available
  let year: number | undefined;
  if (record.created_at) {
    try {
      year = parseInt(record.created_at.slice(0, 4), 10);
      if (isNaN(year)) year = undefined;
    } catch {
      // Ignore parse errors
    }
  }

  return {
    tweet_id: record.tweet_id,
    created_at: record.created_at || '',
    full_text: record.full_text || '',
    username: record.username || 'unknown',
    avatar_media_url: record.avatar_media_url,
    favorite_count: record.favorite_count || 0,
    retweet_count: record.retweet_count || 0,
    quote_count: record.quote_count,
    archive_quote_count: record.archive_quote_count,
    is_archive_user: record.is_archive_user,
    reply_to_tweet_id: record.reply_to_tweet_id,
    reply_to_user_id: record.reply_to_user_id,
    reply_to_username: record.reply_to_username,
    media_urls: record.media_urls,
    year,
    quoted_tweet: quotedTweet,
  };
}

/**
 * Get tweets for a specific year, with pagination.
 */
export async function getTweetsByYear(
  year: string,
  offset: number = 0,
  limit: number = 30
): Promise<Tweet[]> {
  const data = await loadBangersData();
  const tweetIds = data.byYear[year] || [];
  const pageIds = tweetIds.slice(offset, offset + limit);

  const tweets: Tweet[] = [];

  for (const id of pageIds) {
    const record = data.tweets[id];
    if (!record) continue;

    // Get quoted tweet if exists
    const quotedId = data.quoteRelationships.quotedBy[id];
    let quotedTweet: Tweet | undefined;

    if (quotedId) {
      const quotedRecord = data.tweets[quotedId];
      if (quotedRecord) {
        quotedTweet = recordToTweet(quotedRecord);
      }
    }

    const tweet = recordToTweet(record, quotedTweet);
    tweet.quoted_tweet_id = quotedId;
    tweet.column = year;
    tweets.push(tweet);
  }

  return tweets;
}

/**
 * Get top tweets for a year sorted by archive_quote_count.
 * Used to supplement the default byYear ordering (which sorts by total quote_count)
 * so the client has enough data for the archive-quotes view.
 */
export async function getTopArchiveQuoteTweets(
  year: string,
  limit: number = 30
): Promise<Tweet[]> {
  const data = await loadBangersData();
  const tweetIds = data.byYear[year] || [];

  // Sort by archive_quote_count descending
  const sorted = [...tweetIds].sort((a, b) => {
    const recA = data.tweets[a];
    const recB = data.tweets[b];
    return (recB?.archive_quote_count ?? 0) - (recA?.archive_quote_count ?? 0);
  });

  const topIds = sorted.slice(0, limit);
  const tweets: Tweet[] = [];

  for (const id of topIds) {
    const record = data.tweets[id];
    if (!record) continue;

    const quotedId = data.quoteRelationships.quotedBy[id];
    let quotedTweet: Tweet | undefined;
    if (quotedId) {
      const quotedRecord = data.tweets[quotedId];
      if (quotedRecord) {
        quotedTweet = recordToTweet(quotedRecord);
      }
    }

    const tweet = recordToTweet(record, quotedTweet);
    tweet.quoted_tweet_id = quotedId;
    tweet.column = year;
    tweets.push(tweet);
  }

  return tweets;
}

/**
 * Get available years sorted descending.
 */
export async function getAvailableYears(): Promise<string[]> {
  const data = await loadBangersData();
  return Object.keys(data.byYear)
    .filter(y => !isNaN(parseInt(y, 10)))
    .sort((a, b) => parseInt(b, 10) - parseInt(a, 10));
}

/**
 * Check if more tweets are available for a year.
 */
export async function hasMoreTweets(year: string, offset: number): Promise<boolean> {
  const data = await loadBangersData();
  const tweetIds = data.byYear[year] || [];
  return offset < tweetIds.length;
}

/**
 * Search all tweets by text content or username.
 * Scans the full dataset server-side and returns matches grouped by year.
 */
export async function searchTweets(query: string, limit: number = 50): Promise<Tweet[]> {
  const data = await loadBangersData();
  const lowerQuery = query.toLowerCase();
  const results: Tweet[] = [];

  for (const [id, record] of Object.entries(data.tweets)) {
    const text = record.full_text?.toLowerCase() || '';
    const username = record.username?.toLowerCase() || '';
    if (text.includes(lowerQuery) || username.includes(lowerQuery)) {
      const quotedId = data.quoteRelationships.quotedBy[id];
      let quotedTweet: Tweet | undefined;
      if (quotedId) {
        const quotedRecord = data.tweets[quotedId];
        if (quotedRecord) {
          quotedTweet = recordToTweet(quotedRecord);
        }
      }
      const tweet = recordToTweet(record, quotedTweet);
      tweet.quoted_tweet_id = quotedId;

      // Determine year for column grouping
      if (tweet.year) {
        tweet.column = String(tweet.year);
      }

      results.push(tweet);
      if (results.length >= limit) break;
    }
  }

  // Sort by quote_count descending within results
  results.sort((a, b) => (b.quote_count ?? 0) - (a.quote_count ?? 0));

  return results;
}

/**
 * Get the snapshot date as a human-readable string (e.g. "January 2026").
 * Derived from the most recent tweet's created_at field, which reflects
 * when the data is actually from (not when the generation script ran).
 */
export async function getSnapshotDate(): Promise<string> {
  const data = await loadBangersData();

  // Find the latest year key
  const years = Object.keys(data.byYear)
    .filter(y => !isNaN(parseInt(y, 10)))
    .sort((a, b) => parseInt(b, 10) - parseInt(a, 10));

  if (years.length === 0) return '';

  const latestYear = years[0];
  const tweetIds = data.byYear[latestYear] || [];

  // Scan tweets in the latest year to find the most recent created_at
  let maxDate = '';
  for (const id of tweetIds) {
    const record = data.tweets[id];
    if (record?.created_at && record.created_at > maxDate) {
      maxDate = record.created_at;
    }
  }

  if (!maxDate) return '';

  const date = new Date(maxDate);
  return date.toLocaleDateString('en-US', { month: 'long', year: 'numeric' });
}
